# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Chinese'), (2, 'Sushi'), (3, 'Korean'), (4, 'Ramen'), (5, 'Indian'), (6, 'Thai'), (7, 'Mexican'), (8, 'Italian'), (9, 'French'), (10, 'Steakhouse'), (11, 'Bar & Grill'), (12, 'Diner'), (13, 'Casual Dining'), (14, 'Pizza')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(1, 'Happy'), (2, 'Excited'), (3, 'Content'), (4, 'Angry'), (5, 'Nervous'), (6, 'Frustrated'), (7, 'Bored'), (8, 'Lonely'), (9, 'Sad'), (10, 'Indifferent')], default=1)),
                ('stress_level', models.IntegerField(default=0)),
                ('tiredness_level', models.IntegerField(default=0)),
            ],
        ),
    ]
