# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20170516_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='food_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
