# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_person_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.FoodType'),
        ),
    ]
