# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20170520_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='food_type',
        ),
    ]
